# -*- coding: utf-8 -*-
"""22-feb-pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kr6R2g8UaGDWH-E0RbtYQW6DBhgUuSjK

###Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.


###Ans.
"""

import pandas as pd
given_num=([4,8,15,16,23,42])
pandas_series=pd.Series(given_num)
print(pandas_series)

        #OR

pan=pd.Series([4,8,15,16,23,42])
print(pan)

"""###Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the variable print it.

###Ans.
"""

var=pd.Series([1,2,3,4,5,6,7,8,9,10])
var
var.shape         #shape function of series tell us about  the shape of series

var.values

var.size    # size function in series tell us how many values does series contains

var.isnull()   #it check is there any null value in series or not and give result as boolean

var.sort_values(ascending=False)    #sort_values sorted values in ascending or descending acc. to need

"""###Q3. Create a Pandas DataFrame that contains the following data:

Name   --------- Age--------Gender

---

Alice -----------25---------Female


Bob ------------30----------Male

Claire  --------27----------Female

Then,print the dataframe.
"""

from tables import index
data=[['Alice',25,'Female'],
      ['Bob',30,'Male'],
      ['Claire',27,'Female']]

df=pd.DataFrame(data,columns=['Name','Age','Gender'])
df

"""###Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.


###Ans.

One major difference between pandas's series and DataFrame is pandas's series is consists of one column only whereas pandas DataFrame is consist of more than one columns.And that's why data having more than one column is called DataFrame and data having one column is called Series.These Series and DataFrame can holds data of anytype.
"""

series=pd.Series([1,2,3,4,5])
print(series,type(series))    # this is series having 1-D labeled array


data=[['karan',80,12,25],
      ['rahul',78,10,26],
      ['sharman',89,14,26],
      ['ruksana',78,13,27]]
dataframe=pd.DataFrame(data,columns=['name','marks','package','age'])
print(dataframe,type(dataframe))   #this is dataFrame having 2-d labeled arrray

"""###Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can you give an example of when you might use one of these functions?

###Ans.
"""

dataframe

dataframe.set_index('name')   #set_index() functions can be used when you want to make any column as index

dataframe.shape  # with th help of shape method you can find out the no. of rows and columns in a dataframe

dataframe.size  #with help of size uou can find out the no, of values in your dataframe

dataframe.dtypes   # dtypes will provide the datatype of each column

dataframe.columns   # will provide the name of columns in your dataframe

dataframe.info()  #info() function provide the information about dataframe

dataframe.sample()  #sample() will give any row randomly as result from dataframe

dataframe.isnull()   #isnull() function letting us know there is null value in dataframe

"""###Q6. Which of the following is mutable in nature Series, DataFrame, Panel?


###Ans.

All pandas data structures are value-mutable(the values they contain can be altered) but not have always size-mutable.The length of a series cannot changed,but,for example ,columns can be inserted inta a dataframe

###Q7. Create a DataFrame using multiple Series. Explain with an example.
"""

Name=(['Karan','Alice','Rohit','Akangsha','Sam'])
Age=([23,24,22,25,23])
Gender=(['Male','Female','Male','Female','Male'])
country=(['India','USA','Canada','India','London'])
data=pd.DataFrame([Name,Age,Gender,country],index=(['Name','Age','Gender','Country']))
data